# Generated by Django 5.0.4 on 2024-05-19 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('open', 'Open'), ('processing', 'Processing'), ('completed', 'Completed')], max_length=255, null=True),
        ),
    ]
